[project]
name = "jupyterbook"
version = "0.1.0"
description = "Realtime quality control of underwater gliders"
authors = ["Gui Castelao <guilherme@castelao.net>"]
channels = ["conda-forge", "conda", "main"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[tasks]

[dependencies]
jupyter-book = ">=1.0.2,<1.1"
