= Realtime Quality Control for Underwater Gliders

== Credits

(List of contributors including brief description of the contribution(s))

== Statement of Purpose

== Inbox - Content to be processed

Here I'll add texts from our discussions that should be processed and organized
in this new document. Mostly copy-n-paste so we don't loose anything.

Topics that reached a consensus

=== What defines real-time QC?
=== Why do real-time QC?

To answer this we probably need to think about who is the real-time user? Who needs real-time data and can’t wait for the delayed mode? We need to inquire about what they expect from us. What could we do better for them?

Mark: While I agree with Justin that it’s important to know who’s using the data so that QC can be created to meet their needs, I think there are other factors in play. We’ll never know all of the users or how the data is being used (or misused). Operators (data creators) should desire to ensure data quality - all it takes is one obviously bad data point to inform the world that the operator isn’t conducting adequate RT QC, making all data from that source appear less reliable from the user’s point of view.

Gui: I think that the importance of understanding our users is on better defining priorities. I imagine that everyone doing assimilation is already doing their own QC. As operators, we understand our platforms better, so it should be expected that we could do better than them.  The issue is, what are they expecting? It is common on data assimilation to discard anomalous measurements even if those were valid values to avoid a chock in the simulations. On the other side, a monitoring/alerting system cannot afford to miss a single extreme event. For real-time QC we do the best we can, so we should expect errors. What should be our priority?

I agree with Mark that we must do some RT QC. I agree with Justin that we should understand better what is expected from us to serve the community better. Both points are not exclusive and should go together.

(Nikolaos): We should keep in mind that we do real time QC not only for the real-time user but also to ensure that our glider observations have high quality. Sometimes if you have face sensor issues that force you to turn off a sensor to save energy or even recover the glider.
(Gui): That's true. Good point!

"What should be our priority?" (Nicolaos): I think our priority should be to collect high quality observations and ensure high quality in the performance of the suite glider sensors regardless which is the user...this is a great opportunity to create the guideline for this!!!

== Main Document

//Underwater gliders only
This document is focused on underwater gliders, which use changes in buoyancy as the main propulsion, thus characterized by relatively slow propagation velocities.
Other types of platforms with different natures of operation, such as wave gliders and propelled underwater autonomous vehicles, might take advantage of this document but there is no intention on covering specific aspects of those other platforms.

//Do not modify the original data
The methods described here augment the original data to guide the user on the decision of what to trust and hence what to use. The raw data must not be modified, but instead  classification quality flags should be aggregated, therefore, allowing users to apply alternative quality control methods without limitations. For instance, advanced methods might be developed in the future, requiring the original data to avoid error propagation. Quality control in this document does not consider calibration but is limited to a classification. Whenever it is considered important to provide the best data possible ready to use, the recommendation is to aggregate such corrected data while preserving the original values directly available.

//Do not limit to automatic procedures
Real-time QC is commonly associated with automatic checks, which indeed better suit the fast response requirements for a real-time data stream, but it should not be limited to automatic procedures. One of the distinct characteristics of underwater gliders is the close monitoring from pilots and scientists as frequently as hourly to at most every couple of days. 
Complex cases, otherwise missed by the automatic procedures, but identified by the operators should be flagged and updated in the data stream. With the assumption of a low rate of mistakes by the automatic procedure, it is best to do not hold the automatic procedure for manual confirmation, but employ a fast automatic assessment and stream a posterior correction when necessary.

== History

Virtual synchronous meeting on XXX.
(add participants/contributors on each step.

=== Virtual workshop

Between May 11 - 15 2021

(I think we had one single sync meeting. Find the correct date/time, participants, and notes taken)

=== Async discussions from Apr 10 2021 to July 19 2021
Title Best Practices on Realtime QC

=== Called: Main document

Contacted people by email.

Asynchronous discussions through a Google Docs initiated on Feb 2021 and contributions extended up to Oct 2021.

A Google Doc was choosen at that time to reduce the technical barrier and expand
the participation and contributions.

Participants:

* Guilherme Castelao (Gui), castelao@ucsd.edu, Scripps Institution of Oceanography
* Soeren Thomsen, soeren.thomsen@locean.ipsl.fr,	LOCEAN, OceanGliders.org Best Practice coordinator
* Mark Bushnell, mark.bushnell@noaa.gov
* Pierre Testor
* Emma Slater, emmer@bodc.ac.uk
* Justin Buck, juck@bodc.ac.uk
* Mun Woo, mun.woo@uwa.edu.au,	IMOS Ocean Gliders
* Thierry Carval, thierry.carval@ifremer.fr, IFREMER
* Corentin Guyot, corentin.guyot@ifremer.fr, IFREMER
* Sylvie Pouliquen, Sylvie.Pouliquen@ifremer.fr, IFREMER and Euro*Argo ERIC
* Victor Turpin, vturpin@ocean*ops.org, OceanOPS
* Nikolaos Zarokanellos, nzarokanellos@socib.es, SOCIB
* Christoph Waldmann, waldmann@marum.de, MARUM
* Claire Gourcuff, claire.gourcuff@euro-argo.eu


== References

(just a starting point. Move it to bibtex)
